services:
  - type: web
    name: jpvnk
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: JPVNK
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://jpvnk.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-1b9c9db7-jpvnkmedia-2aba.k.aivencloud.com
      - key: DB_PORT
        value: 27306
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: false
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
