<?php

return [
    "lembu" => [
        "american aberdeen",
        "africander",
        "american akaushi",
        "angus",
        "angus plus",
        "ankina",
        "ankolewatusi",
        "american breed",
        "american bucking",
        "amerifax",
        "bali",
        "barzona",
        "beefmaster",
        "belgian blue",
        "belted galloway",
        "black maximizer",
        "blonde d\"aquitaine",
        "bonsmara",
        "braford",
        "brahman",
        "brahmousin",
        "brangus",
        "braunveih",
        "british white",
        "brown swiss",
        "buelingo",
        "canadienne",
        "caracu",
        "charolais",
        "chi-angus",
        "chianina",
        "devon",
        "droughtmaster",
        "dutch belted",
        "eringer",
        "flamande",
        "fleckvieh",
        "galloway",
        "gelbvieh",
        "grauvieh",
        "gyr",
        "hereford (black)",
        "hereford (horned)",
        "hereford (polled)",
        "indu brazil",
        "irish black",
        "kedah-kelantan",
        "limousin",
        "lincoln red",
        "marchigiana",
        "mexican corriente",
        "montbeliarde",
        "murray grey",
        "nellore",
        "normande",
        "piedmontese",
        "red angus",
        "red brahman",
        "red brangus",
        "red dane",
        "santa gertrudis",
        "shorthorn",
        "shorthorn (polled)",
        "simbrah",
        "simmental",
        "south devon",
        "sussex",
        "tabapua",
        "taurindicus",
        "texas longhorn",
        "tuli",
        "wagyu",
        "welsh black",
        "white angus",
        "yellow cattle",
        "yellow cattle x kk",
        "beef crossbreds",
        "dairy x beef crossbreds",
        "australian friesian shaiwal(afs)",
        "australian milking zebu(amz)",
        "ayrshire",
        "friesian",
        "friesian sahiwal",
        "girlando",
        "guernsey",
        "holstein",
        "holstein friesian",
        "jersey",
        "local indian dairy",
        "mafriwal",
        "red & white holstein",
        "red sindhi",
        "sahiwal",
        "international red dairy",
        "milking devon",
        "swedish red and white",
        "dairy crossbreds",
    ],
    "kerbau" => [
        "swamp buffalo",
        "murrah",
        "nilli ravi",
    ],
    "biri-biri" => [
        "american blackbelly sheep, ovi",
        "barbados blackbelly, ovi",
        "black-faced, ovi",
        "bluefaced leicester, ovi",
        "border cheviot, ovi",
        "california red, ovi",
        "california variegated mutant, ovi",
        "cheviot, ovi",
        "columbia, ovi",
        "coopworth, ovi",
        "damara, ovi",
        "dorper, ovi",
        "dorset, ovi",
        "finnish landrace(finn), ovi",
        "\"hairsheep, crossbred\", ovi",
        "hampshire, ovi",
        "horned dorset, ovi",
        "icelandic, ovi",
        "karakul, ovi",
        "leicester, ovi",
        "malin, ovi",
        "merino, ovi",
        "moradanova",
        "polled dorset, ovi",
        "rambouillet, ovi",
        "romanov, ovi",
        "santa ines, ovi",
        "southdown, ovi",
        "suffolk, ovi",
        "targhee, ovi",
        "tunis, ovi",
        "unknown, ovi",
        "wensleydale, ovi",
        "white dorper, ovi",
        "wiltshire horn, ovi",
    ],
    "kambing" => [
        "african dwarf",
        "anglo nubian,cap",
        "angora,cap",
        "alpine,cap",
        "boer,cap",
        "cashmere,cap",
        "golden guernsey,cap",
        "katjang",
        "kiko,cap",
        "la mancha,cap",
        "meat - type crossbred,cap",
        "nigerian dwarf,cap",
        "oberhasli,cap",
        "pygora,cap",
        "pygmy,cap",
        "red kalahari",
        "saanen,cap",
        "sable,cap",
        "savannah,cap",
        "toggenburg,cap",
        "unknown,cap",
    ]
];
