<?php

return [
    'jajahan' => [
        'Kota Bharu' => [
            'daerah' => [
                'Badang',
                'Beta',
                'Kadok',
                'Kemumin',
                'Kota',
                'Kubang Kerian',
                'Limbat',
                'Panji',
                'Pendek',
                'Peringat',
                'Salor',
                'Sering',
                'Bandar Kota Bharu',
            ],
            'kod' => [
                'Badang' => 'BDG',
                'Beta' => 'BTA',
                'Kadok' => 'KDK',
                'Kemumin' => 'KMN',
                'Kota' => 'KOT',
                'Kubang Kerian' => 'KBK',
                'Limbat' => 'LBT',
                'Panji' => 'PNJ',
                'Pendek' => 'PND',
                'Peringat' => 'PRG',
                'Salor' => 'SLR',
                'Sering' => 'SRG',
                'Bandar Kota Bharu' => 'BKB',
            ],
            'poskod' => ['15000', '15050', '15100', '15150', '15200', '15300', '15350', '15400', '16010', '16100', '16150']
        ],
        'Pasir Mas' => [
            'daerah' => [
                'Alor Pasir',
                'Bunut Susu',
                'Chetok',
                'Gual Periok',
                'Kangkong',
                'Kubang Gadong',
                'Kubang Sepat',
                'Lemal',
                'Pasir Mas',
                'Rantau Panjang',
            ],
            'kod' => [
                'Alor Pasir' => 'APR',
                'Bunut Susu' => 'BNS',
                'Chetok' => 'CTK',
                'Gual Periok' => 'GPR',
                'Kangkong' => 'KKG',
                'Kubang Gadong' => 'KGD',
                'Kubang Sepat' => 'KSP',
                'Lemal' => 'LML',
                'Pasir Mas' => 'PSM',
                'Rantau Panjang' => 'RPJ',
            ],
            'poskod' => ['17000', '17010', '17020', '17030', '17040', '17050', '17060', '17070', '17200']
        ],
        'Tumpat' => [
            'daerah' => [
                'Jal Besar',
                'Kebakat',
                'Pengkalan Kubor',
                'Sungai Pinang',
                'Tumpat',
                'Wakaf Bharu',
            ],
            'kod' => [
                'Jal Besar' => 'JLB',
                'Kebakat' => 'KBK',
                'Pengkalan Kubor' => 'PKB',
                'Sungai Pinang' => 'SPN',
                'Tumpat' => 'TPT',
                'Wakaf Bharu' => 'WKB',
            ],
            'poskod' => ['16200', '16210', '16250']
        ],
        'Bachok' => [
            'daerah' => [
                'Bekelam',
                'Gunong',
                'Mahligai',
                'Repek',
                'Tanjung Pauh',
                'Telong',
                'Tawang',
            ],
            'kod' => [
                'Bekelam' => 'BKM',
                'Gunong' => 'GNG',
                'Mahligai' => 'MLG',
                'Repek' => 'RPK',
                'Tanjung Pauh' => 'TJP',
                'Telong' => 'TLG',
                'Tawang' => 'TWG',
            ],
            'poskod' => ['16300', '16310', '16320', '16020']
        ],
        'Pasir Puteh' => [
            'daerah' => [
                'Bukit Abal',
                'Bukit Awang',
                'Bukit Jawa',
                'Gaal',
                'Jeram',
                'Limbongan',
                'Padang Pak Amat',
                'Semerak',
            ],
            'kod' => [
                'Bukit Abal' => 'BKA',
                'Bukit Awang' => 'BKW',
                'Bukit Jawa' => 'BKJ',
                'Gaal' => 'GAL',
                'Jeram' => 'JRM',
                'Limbongan' => 'LBG',
                'Padang Pak Amat' => 'PPA',
                'Semerak' => 'SMR',
            ],
            'poskod' => ['16800', '16810']
        ],
        'Machang' => [
            'daerah' => [
                'Labok',
                'Pangkal Meleret',
                'Pulai Chondong',
                'Temangan',
                'Ulu Sat',
            ],
            'kod' => [
                'Labok' => 'LBK',
                'Pangkal Meleret' => 'PKM',
                'Pulai Chondong' => 'PCD',
                'Temangan' => 'TMG',
                'Ulu Sat' => 'UST',
            ],
            'poskod' => ['18500']
        ],
        'Tanah Merah' => [
            'daerah' => [
                'Bukit Panau',
                'Jedok',
                'Kusial',
                'Sokor',
                'Ulu Kusial',
            ],
            'kod' => [
                'Bukit Panau' => 'BKP',
                'Jedok' => 'JDK',
                'Kusial' => 'KSL',
                'Sokor' => 'SKR',
                'Ulu Kusial' => 'UKS',
            ],
            'poskod' => ['17500', '17510']
        ],
        'Jeli' => [
            'daerah' => [
                'Jeli',
                'Batu Melintang',
                'Kuala Balah',
            ],
            'kod' => [
                'Jeli' => 'JLI',
                'Batu Melintang' => 'BML',
                'Kuala Balah' => 'KBL',
            ],
            'poskod' => ['17600', '17610']
        ],
        'Kuala Krai' => [
            'daerah' => [
                'Batu Mengkebang',
                'Dabong',
                'Guchil',
                'Olak Jeram',
            ],
            'kod' => [
                'Batu Mengkebang' => 'BMK',
                'Dabong' => 'DBG',
                'Guchil' => 'GCH',
                'Olak Jeram' => 'OJR',
            ],
            'poskod' => ['18000', '18200']
        ],
        'Gua Musang' => [
            'daerah' => [
                'Bertam',
                'Chiku',
                'Galas',
                'Pulai',
            ],
            'kod' => [
                'Bertam' => 'BTM',
                'Chiku' => 'CKU',
                'Galas' => 'GLS',
                'Pulai' => 'PLI',
            ],
            'poskod' => ['18300', '18400']
        ],
    ],

    'pejabat' => [
        'Bachok' => [
            'jajahan' => 'Bachok',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن باچوق',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN BACHOK',
            'alamat_baris1' => 'JALAN KAMPUNG NIPAH, 16300 BACHOK',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-7788242',
            'faks' => '09-7780675',
            'kod' => 'B',
            'kod_rujukan' => 'JPVB',
        ],
        'Kota Bharu' => [
            'jajahan' => 'Kota Bharu',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن كوتا بهارو',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN KOTA BHARU',
            'alamat_baris1' => 'JALAN KUBANG KACHANG, 15200 KOTA BHARU',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-7445566',
            'faks' => '09-7445577',
            'kod' => 'KB',
            'kod_rujukan' => 'JPVKB',
        ],
        'Pasir Mas' => [
            'jajahan' => 'Pasir Mas',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن ڤاسير مس',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN PASIR MAS',
            'alamat_baris1' => 'JALAN TASEK, 17000 PASIR MAS',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-7909242',
            'faks' => '09-7900675',
            'kod' => 'PM',
            'kod_rujukan' => 'JPVPM',
        ],
        'Tumpat' => [
            'jajahan' => 'Tumpat',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن تومڤت',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN TUMPAT',
            'alamat_baris1' => 'JALAN DATO BIKAM, 16200 TUMPAT',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-7257242',
            'faks' => '09-7257675',
            'kod' => 'T',
            'kod_rujukan' => 'JPVT',
        ],
        'Pasir Puteh' => [
            'jajahan' => 'Pasir Puteh',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن ڤاسير ڤوتيه',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN PASIR PUTEH',
            'alamat_baris1' => 'JALAN NIK MAT SAMAN, 16800 PASIR PUTEH',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-7866242',
            'faks' => '09-7860675',
            'kod' => 'PP',
            'kod_rujukan' => 'JPVPP',
        ],
        'Machang' => [
            'jajahan' => 'Machang',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن ماچڠ',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN MACHANG',
            'alamat_baris1' => 'JALAN PEJABAT POS, 18500 MACHANG',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-9751242',
            'faks' => '09-9750675',
            'kod' => 'M',
            'kod_rujukan' => 'JPVM',
        ],
        'Tanah Merah' => [
            'jajahan' => 'Tanah Merah',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن تانه ميره',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN TANAH MERAH',
            'alamat_baris1' => 'JALAN KELANTAN, 17500 TANAH MERAH',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-9556242',
            'faks' => '09-9550675',
            'kod' => 'TM',
            'kod_rujukan' => 'JPVTM',
        ],
        'Jeli' => [
            'jajahan' => 'Jeli',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن جيلي',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN JELI',
            'alamat_baris1' => 'JALAN HOSPITAL, 17600 JELI',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-9440242',
            'faks' => '09-9440675',
            'kod' => 'J',
            'kod_rujukan' => 'JPVJ',
        ],
        'Kuala Krai' => [
            'jajahan' => 'Kuala Krai',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن كوالا كراي',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN KUALA KRAI',
            'alamat_baris1' => 'JALAN SULTAN YAHYA PETRA, 18000 KUALA KRAI',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-9666242',
            'faks' => '09-9660675',
            'kod' => 'KK',
            'kod_rujukan' => 'JPVKK',
        ],
        'Gua Musang' => [
            'jajahan' => 'Gua Musang',
            'jawi' => 'جابتن ڤرخدمتن ۏيترينر ججاهن ڬوا موسڠ',
            'nama' => 'PEJABAT PERKHIDMATAN VETERINAR',
            'jajahan_title' => 'JAJAHAN GUA MUSANG',
            'alamat_baris1' => 'TINGKAT 1, WISMA PERSEKUTUAN, 18300 GUA MUSANG',
            'alamat_baris2' => 'KELANTAN DARUL NAIM',
            'tel' => '09-9121242',
            'faks' => '09-9120675',
            'kod' => 'GM',
            'kod_rujukan' => 'JPVGM',
        ],
    ],
];
